#pragma once
#include "Base.h"
#include "Client_Defines.h"

NS_BEGIN(Client)

class CKhazan_SoundHelper final : public CBase
{
public:
	typedef struct tagPlayerSoundGroup
	{
		vector<_wstring> SoundKeys;

		size_t CurrentIndex = { 0 };

		_wstring Get_NextKey()
		{
			if ( SoundKeys.empty() ) return TEXT("");

			_wstring keyToPlay = SoundKeys[ CurrentIndex ];
			CurrentIndex = ( CurrentIndex+1 )% SoundKeys.size();
			return keyToPlay;
		}

	}SOUND_GROUP;

	enum PC_SOUND_CHANNEL { WEAPON, MOVE, VOICE, INTERACTION, EFFECT1, EFFECT2, CHNNEL_END };

	enum PC_SOUND_GROUPTYPE {
		IDLE,
		IDLE_RATTLE,

		MOVE_INJURE_L,
		MOVE_INJURE_R,
		MOVE_WALK,
		MOVE_RUN,
        MOVE_SPRINT_START,
        MOVE_SPRINT,
		MOVE_SPRINT_STOP,
		MOVE_SPRINT_RATTLE,
		MOVE_DODGE_FRONT,
		MOVE_DODGE_REAR,
		MOVE_DODGE_SIDE,
		MOVE_FALL,
		MOVE_RANDING,
		MOVE_CLIMB,
		MOVE_CLIMB_END,

		ATTACK_SPEAR_WEAK1,
		ATTACK_SPEAR_WEAK2,
		ATTACK_SPEAR_WEAK3,
		ATTACK_SPEAR_WEAK_CHARGING_START,
		ATTACK_SPEAR_WEAK_CHARGING,
		ATTACK_SPEAR_WEAK_CHARGING_ATTACK,
		ATTACK_SPEAR_WEAK_CHARGING_IMPACT,
		ATTACK_SPEAR_STRONG1,
		ATTACK_SPEAR_STRONG2,
		ATTACK_SPEAR_STRONG2_FOLEY,
		ATTACK_SPEAR_STRONG3,
        ATTACK_SPEAR_STRONG3_FOLEY,
		ATTACK_SPEAR_STRONG_CHARGING_START,
		ATTACK_SPEAR_STRONG_CHARGING,
		ATTACK_SPEAR_STRONG_CHARGING_ATTACK,
		ATTACK_SPEAR_STRONG_CHARGING_IMPACT,
		ATTACK_SPEAR_DODGE,
		ATTACK_SPEAR_WEAK_SPRINT,
		ATTACK_SPEAR_STRONG_SPRINT,
        ATTACK_SPEAR_BRUTAL1_START,
		ATTACK_SPEAR_BRUTAL1,
		ATTACK_SPEAR_BRUTAL2,
		ATTACK_SPEAR_FALL,
		SKILL_SPEAR_MOONLIGHT_SLASH,					//달빛 베기
		SKILL_SPEAR_FULL_MOON,							//보름달
		SKILL_SPEAR_SHADOW_SLASH,						//그림자 베기
		SKILL_SPEAR_SPIRAL_THRUST_START,				//나선 찌르기
		SKILL_SPEAR_SPIRAL_THRUST_IMPACT,
		SKILL_SPEAR_SPIRAL_THRUST_END,
		SKILL_SPEAR_SPIRAL_THRUST_WHIRLWIND_START,		//나선 찌르기 : 소용돌이
		SKILL_SPEAR_SPIRAL_THRUST_WHIRLWIND_IMPACT,
		SKILL_SPEAR_SPIRAL_THRUST_WHIRLWIND_END,
		SKILL_SPEAR_ASSAULT,							//강습
		SKILL_SPEAR_MOMENT_SLASH,						//찰나 베기
		SKILL_SPEAR_CRITICAL_STRIKE,					//급소 타격
		SKILL_SPEAR_SHADOW_CLEAVE_START,				//그림자 참격
		SKILL_SPEAR_SHADOW_CLEAVE_IMPACT,

        SPEAR_POSE_RETURN,

		ATTACK_GS_WEAK1,
		ATTACK_GS_WEAK1_IMPACT,
		ATTACK_GS_WEAK2,
		//ATTACK_GS_WEAK2_IMPACT,
		ATTACK_GS_WEAK3,
		ATTACK_GS_WEAK3_IMPACT,
		ATTACK_GS_WEAK3_FOLEY ,
		ATTACK_GS_WEAK1_CHARGING,
		ATTACK_GS_WEAK1_CHARGING_ATTACK,
		ATTACK_GS_WEAK2_CHARGING,
		ATTACK_GS_WEAK2_CHARGING_ATTACK,
		ATTACK_GS_STRONG,
		ATTACK_GS_STRONG_CHARGING,
		ATTACK_GS_STRONG_CHARGING_ATTACK,
		ATTACK_GS_DODGE_ATTACK,
		ATTACK_GS_DODGE_IMPACT,
		ATTACK_GS_BRUTAL_START,
		ATTACK_GS_BRUTAL1,
		ATTACK_GS_BRUTAL2,
		ATTACK_GS_FALL,
		SKILL_GS_BREATHTAKING_START,							//숨통끊기
		SKILL_GS_BREATHTAKING_ATTACK,							
		SKILL_GS_BREATHTAKING_SUCCESS,							
		SKILL_GS_BREATHTAKING_EMBRYONIC_START,					//숨통끊기 : 태동
		SKILL_GS_BREATHTAKING_EMBRYONIC_ATTACK,				
		SKILL_GS_BREATHTAKING_EMBRYONIC_SUCCESS,				
		SKILL_GS_BREATHTAKING_BLOODSHED_CHARGING,				//숨통끊기 : 선혈
		SKILL_GS_BREATHTAKING_BLOODSHED_CHARGING_SUCCESS,			
		SKILL_GS_BREATHTAKING_BLOODSHED_ATTACK,			
		SKILL_GS_BREATHTAKING_BLOODSHED_SUCCESS,			
		SKILL_GS_GIANTHUNT_CHARGING,							//거인사냥
		SKILL_GS_GIANTHUNT_ATTACK,								
		SKILL_GS_PHANTOM_SHADOWOFDARKNESS_CHARGING,				//귀신 : 어둠의 그림자
		SKILL_GS_PHANTOM_SHADOWOFDARKNESS_ATTACK,				
		SKILL_GS_LIMIT_BREAK_CHARGING,							//한계극복
		SKILL_GS_LIMIT_BREAK_LOOP,							
		SKILL_GS_LIMIT_BREAK_ATTACK,							
		SKILL_GS_LIMIT_BREAK_END,							
		SKILL_GS_BREAK_THROUGH_CHARGING,							//정면돌파		
		SKILL_GS_BREAK_THROUGH_ATTACK,							
		SKILL_GS_WARCRY_CHARGING,								//거대한 포효	
		SKILL_GS_WARCRY_ATTACK,							
		SKILL_GS_INNER_FURY_CHARGING,							//내제된분노		
		SKILL_GS_INNER_FURY_CHARGING_SUCCESS,						
		SKILL_GS_INNER_FURY_ATTACK,					

		DAMAGED_NORMAL,
		DAMAGED_HARD,		//피가 많이 깍였을 때

		GUARD_ON_SPEAR,
		GUARD_ON_GS,
        GUARD_FOLEY,
        GUARD_SUCCESS,
		GUARD_OFF_SPEAR,
		GUARD_OFF_GS,

		JUSTGUARD_EFFECT,
		JUSTGUARD,

		INTERACTION_LACRIMA_ON,
		INTERACTION_LACRIMA_OFF,
		INTERACTION_LACRIMA_GAIN,
		INTERACTION_LACRIMA_GET,
		INTERACTION_HEAL,
		INTERACTION_LANTERN_ON,
		INTERACTION_LANTERN_OFF,
		INTERACTION_FRIENDLY,
		INTERACTION_STATUE,
		INTERACTION_SPEAR_ARMED,
		INTERACTION_SPEAR_UNARMED,
		INTERACTION_GS_ARMED,
		INTERACTION_GS_UNARMED,


		PC_SOUND_GROUPTYPE_END,
	};



private:
	CKhazan_SoundHelper();
	virtual ~CKhazan_SoundHelper() = default;

public:
	HRESULT					Initialize();

    const TCHAR*			Get_NextSoundKey(PC_SOUND_GROUPTYPE type, PC_SOUND_CHANNEL eChannel);

private:
	unordered_map<PC_SOUND_GROUPTYPE, SOUND_GROUP>  AllSoundGroups;

    _wstring    m_strLastKey[CHNNEL_END] = {};

private:
	void	MakeSoundKeyHelper(_wstring baseKey, size_t count, vector<_wstring>& resultKeys);

public:
	static CKhazan_SoundHelper*	Create();
	virtual void				Free();


};

NS_END
